### ISSUE TITLE
Install instructions on operator hub no-longer work

### ISSUE THREAD

**Issue by tibcoplord** [m88i/nexus-operator#152] opened 2020-09-17 17:01 UTC
**Describe the bug**

Following the instructions at https://operatorhub.io/operator/nexus-operator-m88i/alpha/nexus-operator.v0.3.0 no-longer works ... at least with docker desktop on the mac.

**To Reproduce**

With fresh kubernetes

curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.16.1/install.sh | bash -s 0.16.1
kubectl create -f https://operatorhub.io/install/alpha/nexus-operator-m88i.yaml
kubectl get csv -n my-nexus-operator-m88i

So far so good 👍 

NAME                    DISPLAY          VERSION   REPLACES                PHASE
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   Succeeded

But loading the sample yaml (kind Nexus) does nothing - nexus is not started.

**Expected behavior**

Nexus instance started

**Environment**

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"2576e482bf003e34e67ba3d69edcf5d411cfd6f3", GitTreeState:"clean", BuildDate:"2020-05-12T06:50:39Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

I did notice that nexus starts in namespace my-nexus-operator-m88i ... ie -

apiVersion: apps.m88i.io/v1alpha1
kind: Nexus
metadata:
  name: nexus3
  namespace: my-nexus-operator-m88i
spec:
  networking:
    expose: false
  persistence:
    persistent: false
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  useRedHatImage: false

**Comment by ricardozanini** [comment] 2020-09-17 21:45
Hi @tibcoplord 
Many thanks for reaching out!

Your Nexus instance supposed to be created in the same namespace, `my-nexus-operator-m88i`. The operator does not watch all namespaces any more, we are going to change that for 0.6. Can you try installing the Nexus instance in the same namespace which the operator is installed?

Sorry for the late reply, just come to my attention now.

**Comment by LCaparelli** [comment] 2020-09-17 22:04
Hi @tibcoplord thanks for bringing this to our attention!

I was unable to reproduce running minikube on Linux. Take with a grain of salt due to the platform differences, but please have a look at the steps I took and let me know if you did anything differently. This was done on a fresh minikube VM.

```
╰─ curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.16.1/install.sh | bash -s 0.16.1
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com condition met
namespace/olm created
namespace/operators created
serviceaccount/olm-operator-serviceaccount created
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager created
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm created
deployment.apps/olm-operator created
deployment.apps/catalog-operator created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view created
operatorgroup.operators.coreos.com/global-operators created
operatorgroup.operators.coreos.com/olm-operators created
clusterserviceversion.operators.coreos.com/packageserver created
catalogsource.operators.coreos.com/operatorhubio-catalog created
Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
deployment "olm-operator" successfully rolled out
Waiting for deployment "catalog-operator" rollout to finish: 0 of 1 updated replicas are available...
deployment "catalog-operator" successfully rolled out
Package server phase: Installing
Package server phase: Succeeded
deployment "packageserver" successfully rolled out
╰─ kubectl create -f https://operatorhub.io/install/alpha/nexus-operator-m88i.yaml
namespace/my-nexus-operator-m88i created
operatorgroup.operators.coreos.com/operatorgroup created
subscription.operators.coreos.com/my-nexus-operator-m88i created
╰─ kubectl get csv -n my-nexus-operator-m88i -w
NAME                    DISPLAY          VERSION   REPLACES                PHASE
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   Pending
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   InstallReady
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   InstallReady
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   Installing
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   Installing
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   Installing
nexus-operator.v0.3.0   Nexus Operator   0.3.0     nexus-operator.v0.2.1   Succeeded
╰─ echo "apiVersion: apps.m88i.io/v1alpha1
kind: Nexus
metadata:
  name: nexus3
spec:
  networking:
    expose: false
  persistence:
    persistent: false
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  useRedHatImage: false" | kubectl -n my-nexus-operator-m88i apply -f -
nexus.apps.m88i.io/nexus3 created
╰─ kubectl -n my-nexus-operator-m88i get pods
NAME                             READY   STATUS              RESTARTS   AGE
nexus-operator-b48c54d4b-tb5g7   1/1     Running             0          59s
nexus3-c8ffc8b8f-45t64           0/1     ContainerCreating   0          5s
╰─ minikube version  
minikube version: v1.13.0
commit: 0c5e9de4ca6f9c55147ae7f90af97eff5befef5f-dirty
╰─ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tibcoplord** [comment] 2020-09-18 05:37
Yes, installing in my-nexus-operator-m88i works.  So at least the example yaml on operator hub needs to be updated with that.

Thanks!

**Comment by tibcoplord** [comment] 2020-09-18 05:42
> kubectl -n my-nexus-operator-m88i apply -f -

Yes, this works for me as well.  Its a change thats not mentioned on the operator hub.

It makes quite a difference to my install  - I need to go through and update all the hostnames that reference the nexus instance since I can no-longer run nexus in the current namespace.  This changes especially hurts since the previous version is no-longer available.

**Comment by ricardozanini** [comment] 2020-09-18 09:54
@tibcoplord do you mind sharing how do you use and install the operator? I can send an update to have this back. 

If you have one Nexus instance installed and the operator in another namespace, you would have to install it in the same namespace. 

You could use our installation script to install it if you don’t need OLM to be installed in your cluster.

**Comment by ricardozanini** [comment] 2020-09-18 10:09
Nevertheless, I've sent a PR to add this setup back: https://github.com/operator-framework/community-operators/pull/2355

If we can't modify the current version, I will upgrade to 0.3.1 if that helps, @tibcoplord

**Comment by tibcoplord** [comment] 2020-09-18 10:15
> @tibcoplord do you mind sharing how do you use the operator? I can send an update to have this back.

Its actually pretty straightforward :

* Start nexus instance in namespace "fred"
* Add artifacts to nexus
* Start application in namespace "fred"
* Application accesses nexus via http://nexus/...

ie using a hostname local to the namespace ( since both are in the same namespace ).

**Comment by ricardozanini** [comment] 2020-09-18 12:02
But in this setup the operator is installed in the namespace "fred"?

We should get this feature back soon, the PR has been accepted.

**Comment by LCaparelli** [comment] 2020-09-21 18:22
@tibcoplord we've added back the option to manage multiple namespaces. Would you mind following the install instructions from [Operator Hub](https://operatorhub.io/operator/nexus-operator-m88i) again and letting us know if your previous method of deployment is back to working as expected?

**Comment by tibcoplord** [comment] 2020-09-21 20:42
Many thanks for the update - much appreciated.

I see the same image issue - https://quay.io/repository/operatorhubio/nexus-operator-m88i?tag=latest&tab=tags doesn't have 0.3.0.  Maybe syncs just take a bit of time.

**Comment by ricardozanini** [comment] 2020-09-21 20:46
Yeah, something might went wrong, I'll try to contact them

**Comment by LCaparelli** [comment] 2020-09-22 12:13
@tibcoplord it seems it synced up a couple of hours ago. I just tested on my minikube and things are looking good. Can you let us know if things at your end got fixed too?

**Comment by ricardozanini** [comment] 2020-09-22 12:34
Oh, actually was not synced, was manually fixed. :)

Looks like we can't change the manifest in the same version.

**Comment by tibcoplord** [comment] 2020-09-22 12:53
Yep ... back working again for me.

Many thanks for your prompt fix !

**Comment by ricardozanini** [comment] 2020-09-22 14:30
Thanks for the feedback, @tibcoplord! I'm closing this one.

**Closed by ricardozanini** 2020-09-22 14:30 UTC
Labels: bug :bug:
